### ISSUE TITLE
Where the fuck are all those chinese users coming from

### ISSUE THREAD

**Issue by Pizzacus** [Pizzacus/satania.moe#27]
Title

![image](https://user-images.githubusercontent.com/7659613/40915916-175db030-67fe-11e8-9896-1e7046a8e5dd.png)

**Comment by ambjoorn94** [comment]
Sounds very serious...

**Comment by Pizzacus** [comment]
Tagged

**Comment by ghost** [comment]
China

**Comment by Pizzacus** [comment]
Aaaaaaah makes sense ~~I meant from where on the internet but at this point, I guess we'll never know~~
