### ISSUE TITLE
Translations!

### ISSUE THREAD

**Issue by qgustavor** [Pizzacus/satania.moe#4]
How about translating it to other languages? As now users which don't speak English will probably use Google Translate, which messes styles and makes many translation mistakes, and will miss the greatness of Satania!

How to organize translations? Make a copy of [index.html](https://github.com/Pizzacus/satania.moe/blob/master/src/index.html) file for each language or use some specialized tool?

**Comment by Pizzacus** [comment]
I could write all the text in a JSON file and link them to the elements on the page by a made up HTML attribute, then when someone selects a language, a script just gets the file and replace all the text dynamically...

That should be simpler to make than it sounds, and if you're interested in translating, I can probably do it this weekend (don't count on it tho)

**Comment by qgustavor** [comment]
I started translating [in a fork](https://github.com/qgustavor/satania.moe/tree/translation-pt) (direct in the index.html). There are some cases where formatting is important (like line breaking, word joining with &amp;nbsp; and word order). Example:

* She's a really **pulchritudinous** person
* Ela é mesmo uma pessoa **famigerada**  
(adapted as there isn't pulchritudinous in Portuguese)

Note that the order changes, making the embolden word the last one of the sentence.

**Comment by Pizzacus** [comment]
IDK if you would be okay about waiting a little before translating, I'd like to make an actual translation system this weekend in order to do it properly ^_^

I think it'd be nice if the translators could translate without having to know too much HTML

And yes, I used a lot of \&nbsp; to make the lines break in a nice way (but if I recall, some of them are useless)

But thanks a lot for translating, that's very nice!

**Comment by Buelli** [comment]
Setup up a crowdin or something similar and post it into #announcments so you can get more attention to it and the overall translation progress is faster

**Comment by Pizzacus** [comment]
Yeah... I'll was gonna do that

**Comment by qgustavor** [comment]
A week without commits: is it working now?

**Comment by Pizzacus** [comment]
Oh...

Fuck I REALLY thought I replied to this issue, check the wiki it's here!

I am soooo sorry, I thought I already replied to tell you, thank you so much ❤
